version: "3.8"

services:
  franzmq:
    build: .
    container_name: franzmq
    ports:
      - "8080:8080"
      - "6060:6060"
    volumes:
      - .:/app
      - /app/data
    restart: always
    working_dir: /app
    command: go run main.go
    networks:
      - franzmq_net
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # Ensure OpenTelemetry exporter points to Jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OpenTelemetry gRPC
      - "4318:4318"   # OpenTelemetry HTTP
    networks:
      - franzmq_net

networks:
  franzmq_net:
