version: "3.8"

services:
  franzmq:
    build: .
    container_name: franzmq
    ports:
      - "8080:8080"
      - "6060:6060"
    volumes:
      - .:/app
      - /app/data
    restart: always
    working_dir: /app
    command: go run main.go
    depends_on:
      etcd:
        condition: service_healthy
    networks:
      - franzmq_net

  etcd:
    image: quay.io/coreos/etcd:v3.5.7
    container_name: etcd
    command: >
      /usr/local/bin/etcd
      --data-dir=/etcd-data
      --name=etcd-node
      --advertise-client-urls=http://0.0.0.0:2379
      --listen-client-urls=http://0.0.0.0:2379
      --initial-advertise-peer-urls=http://0.0.0.0:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-cluster=etcd-node=http://0.0.0.0:2380
    volumes:
      - etcd-data:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - franzmq_net

networks:
  franzmq_net:

volumes:
  etcd-data:
