name: Go Test CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install etcd
        run: |
          sudo apt-get update
          sudo apt-get install -y etcd
          nohup etcd --advertise-client-urls=http://127.0.0.1:2379 --listen-client-urls=http://127.0.0.1:2379 > /dev/null 2>&1 &

      - name: Verify etcd is running
        run: |
          sleep 5
          etcdctl --endpoints=http://127.0.0.1:2379 endpoint status
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4 

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...
